name: Build EfficientDynamoDb

on:
  workflow_dispatch:
  push:
    branches:
      - devtekve
    tags:
      - 'effddb-v*'
    paths:
      - 'src/**'
  pull_request:
    branches:
      - devtekve
    paths:
      - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --no-build --configuration Release
    - name: Publish to NuGet
      if: ${{ github.ref == 'refs/heads/devtekve' || startsWith(github.ref, 'refs/tags/effddb-v') }}
      run: |
        dotnet pack -p:PackageId=DevTekVE.EfficientDynamoDb -p:Description="This is a fork for own development. Use at your own Risk. No guarantees are made." --no-build -c Release src/EfficientDynamoDb/EfficientDynamoDb.csproj -o .
        dotnet nuget push *.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}} --skip-duplicate
